
CREATE SEQUENCE  "LAB2_PRODUCTS_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 4 CACHE 128;

CREATE SEQUENCE  "LAB2_CATEGORY_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 4 CACHE 128;

-- CREATE SEQUENCE  "LAB2_USERS_SEQ"  MINVALUE 1 MAXVALUE 9999999999 INCREMENT BY 1 START WITH 3 CACHE 128;
--
-- CREATE TABLE "LAB2_USERS"
-- (
--     "USER_ID" NUMBER NOT NULL ENABLE,
--     "USERNAME" VARCHAR2(50) NOT NULL ENABLE,
--     "PASSWORD" VARCHAR2(50) NOT NULL ENABLE,
--     "ROLE" VARCHAR2(50) NOT NULL ENABLE,
--     "ENABLED" CHAR(1) NOT NULL ENABLE,
--     CONSTRAINT "LAB2_USER_PK" PRIMARY KEY ("USER_ID")
-- );

CREATE TABLE "LAB2_PRODUCTS"
(
    "PRODUCT_ID" NUMBER NOT NULL ENABLE,
    "PRODUCT_NAME" VARCHAR2(100) NOT NULL ENABLE,
    "PRODUCT_PRISE" NUMBER NOT NULL ENABLE,
    "CATEGORY_ID" NUMBER,
    CONSTRAINT "LAB2_PRODUCTS_PK" PRIMARY KEY (PRODUCT_ID)
);

CREATE TABLE "LAB2_CATEGORY"
(
    "CATEGORY_ID" NUMBER NOT NULL ENABLE,
    "CATEGORY_NAME" VARCHAR2(100) NOT NULL ENABLE,
    CONSTRAINT "LAB2_CATEGORY_PK" PRIMARY KEY (CATEGORY_ID)
);

ALTER TABLE LAB2_PRODUCTS ADD CONSTRAINT "LAB2_PRODUCTS_FK" FOREIGN KEY (CATEGORY_ID)
REFERENCES LAB2_CATEGORY (CATEGORY_ID) ON DELETE SET NULL ENABLE;