
INSERT INTO LAB2_ROLES(ROLE_ID, ROLE_NAME) VALUES (1, 'ROLE_ADMIN');
INSERT INTO LAB2_ROLES(ROLE_ID, ROLE_NAME) VALUES (2, 'ROLE_USER');

INSERT INTO LAB2_USERS(USER_ID, USERNAME, PASSWORD, ROLE_ID, ENABLE) VALUES (1, 'admin', 'admin', 1, 1);
INSERT INTO LAB2_USERS(USER_ID, USERNAME, PASSWORD, ROLE_ID, ENABLE) VALUES (2, 'user', 'user', 2, 1);

INSERT INTO LAB2_CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES (1, 'No category');
INSERT INTO LAB2_CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES (2, 'Computers');
INSERT INTO LAB2_CATEGORY(CATEGORY_ID, CATEGORY_NAME) VALUES (3, 'Games');

INSERT INTO LAB2_PRODUCTS(PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRISE, CATEGORY_ID) VALUES (1, 'HYPER ULTRA GAMING PC', 900, 2);
INSERT INTO LAB2_PRODUCTS(PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRISE, CATEGORY_ID) VALUES (2, 'God of War', 3999, 3);
INSERT INTO LAB2_PRODUCTS(PRODUCT_ID, PRODUCT_NAME, PRODUCT_PRISE, CATEGORY_ID) VALUES (3, 'Half-Life 3', 699, 3);

